### ISSUE TITLE
obol user management: non-root users have access to obol data

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#152]
Logged in as Jane, a power-user in login-b.vc-b, can extract data including passwords for all other users. Only the tenant(root) should be able to do so. 

-bash-4.2$ whoami
jane
-bash-4.2$ obol user show jane
{'uid': ['jane'], 'objectClass': ['top', 'person', 'organizationalPerson', 'inetOrgPerson', 'posixAccount', 'shadowAccount'], 'loginShell': ['/bin/bash'], 'userPassword': ['123'], 'uidNumber': ['1051'], 'gidNumber': ['1051'], 'sn': ['Smith'], 'homeDirectory': ['/home/jane'], 'givenName': ['Jane'], 'cn': ['Jane']}
-bash-4.2$ obol user show john
{'uid': ['john'], 'objectClass': ['top', 'person', 'organizationalPerson', 'inetOrgPerson', 'posixAccount', 'shadowAccount'], 'loginShell': ['/bin/bash'], 'userPassword': ['123'], 'uidNumber': ['1050'], 'gidNumber': ['1050'], 'sn': ['Smith'], 'homeDirectory': ['/home/john'], 'givenName': ['John'], 'cn': ['John']}
-bash-4.2$ whoami
jane

**Comment by themisa** [comment]
Regular users also have access to obol

**Comment by abhimukh** [comment]
Now, only the root user should have execute permission for obol.

**Comment by hansthen** [comment]
This should also be checked against the ldap server. Do not close this yet, as there is a security flaw in obol.

**Comment by themisa** [comment]
not fixed:
bash-4.2$ whoami
jane
bash-4.2$ obol user show jane
{'uid': ['jane'], 'objectClass': ['top', 'person', 'organizationalPerson', 'inetOrgPerson', 'posixAccount', 'shadowAccount'], 'loginShell': ['/bin/bash'], 'userPassword': ['123'], 'uidNumber': ['1051'], 'gidNumber': ['1051'], 'sn': ['Smith'], 'homeDirectory': ['/home/jane'], 'givenName': ['Jane'], 'cn': ['Jane']}
bash-4.2$ obol user show john
{'uid': ['john'], 'objectClass': ['top', 'person', 'organizationalPerson', 'inetOrgPerson', 'posixAccount', 'shadowAccount'], 'loginShell': ['/bin/bash'], 'userPassword': ['123'], 'uidNumber': ['1050'], 'gidNumber': ['1050'], 'sn': ['Smith'], 'homeDirectory': ['/home/john'], 'givenName': ['John'], 'cn': ['John']}

**Comment by abhimukh** [comment]
There was a typo in trinity_login/etc/trinity/login.conf. It should be fixed in 7f25038.

**Comment by hansthen** [comment]
@themisa: do not close this as protecting the executable does not fix the protocol error. We should configure the LDAP server to not divulge passwords.

**Comment by hansthen** [comment]
Actually, it is not the LDAP server, password hashing should be enabled inside obol.

**Comment by themisa** [comment]
-bash-4.2$ whoami
jane
-bash-4.2$ obol user show jane
-bash: /usr/sbin/obol: Permission denied
-bash-4.2$ obol user show john
-bash: /usr/sbin/obol: Permission denied

Fixed in version * r3
e755ef5
