### ISSUE TITLE
nova compute node: loses ip addr 

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#386]
**Version:** r5_fixes c2dc5c0
**Environment:** amaster

The nova compute node lost ip addr. Cannot ping/ssh into the node.

**Comment by hansthen** [comment]
What do you mean "lost"? Did it happen overnight?

**Comment by themisa** [comment]
Yes overnight.

**Comment by abhimukh** [comment]
@hansthen : Do we do anything special for the trinity/compute  profile to ensure that the nodes do not lose their IP?

**Comment by abhimukh** [comment]
@themisa I need more info to debug this. Next time this happens, I will need to poke around in the system, or you can save /var/log/messages somewhere.

**Comment by hansthen** [comment]
@abhimukh Is this fixed in the right branch? It looks only fixed in master.

**Comment by themisa** [comment]
**Version:** r6 cc03c73
**Environment:** tmaster

```
"centos7-x86_64-netboot-nova",,"nova","linux",,"netboot",,"centos7-x86_64",,,"Linux","centos7","x86_64",,,"cv_configure_prinic,cv_install_nova,cv_install_agent"
```

The fix is in this version, but i still cannot ping the nova node the next day:

```
[root@controller(unknown*) ~]# ping node002
PING node002 (10.141.0.2) 56(84) bytes of data.
From controller (10.141.255.254) icmp_seq=1 Destination Host Unreachable
From controller (10.141.255.254) icmp_seq=2 Destination Host Unreachable
From controller (10.141.255.254) icmp_seq=3 Destination Host Unreachable
From controller (10.141.255.254) icmp_seq=4 Destination Host Unreachable
```

**Comment by themisa** [comment]
Not fixed in:
**Version:** r6 8009399
**Environment:** tmaster

```
[root@controller(tmaster) ~]# ping node002
PING node002 (10.141.0.2) 56(84) bytes of data.
From controller (10.141.255.254) icmp_seq=1 Destination Host Unreachable
From controller (10.141.255.254) icmp_seq=2 Destination Host Unreachable
From controller (10.141.255.254) icmp_seq=3 Destination Host Unreachable
```

**Comment by hansthen** [comment]
```
[root@node002 ~]# ps -ef | grep dhc
root      1991  1963  0 05:24 pts/0    00:00:00 grep --color=auto dhc
[root@node002 ~]# systemctl restart network
[root@node002 ~]# ps -ef | grep dhc
root      2443     1  0 05:25 ?        00:00:00 /sbin/dhclient -H node002 -1 -q -lf /var/lib/dhclient/dhclient-eno1.leases -pf /var/run/dhclient-eno1.pid eno1
```

**Comment by hansthen** [comment]
@themisa can you retest this in R6 or R7?

**Comment by themisa** [comment]
@hansthen so fix is not in r6_fixes? what is commit SHA?

In r6_fixes it doesn't work still.

```
[root@controller(tmaster) ~]# ssh node002
ssh: connect to host node002 port 22: No route to host
```

**Comment by themisa** [comment]
Not fixed in r7 either

**Version:** r7 4dc20f7
**Environment:** dmaster


node003, node004 were nova compute.
```
[root@controller(dmaster) ~]# ssh node003
ssh: connect to host node003 port 22: No route to host
[root@controller(dmaster) ~]# ssh node004
ssh: connect to host node004 port 22: No route to host
```
