### ISSUE TITLE
ssh from node to node ask if you trust the ssh key

### ISSUE THREAD

**Issue by dchirikov** [clustervision/trinity#519]
needs to be disabled

**Comment by hansthen** [comment]
Unable to reproduce in R6. Please check the contents of 

```
[root@login ~]# cat /etc/skel/.ssh/config
UserKnownHostsFile /dev/null
Host *
	StrictHostKeyChecking no
LogLevel QUIET

```

**Comment by dchirikov** [comment]
related to #520

**Comment by hansthen** [comment]
This was fixed in R6.

**Comment by brunopereira81** [comment]
This configuration makes ssh fail silently on each fault, even when you are trying to reach a invalid node:
```
[root@controller(magdeburg*) ~]# ssh node012 #good node not available
[root@controller(magdeburg*) ~]# ssh node12 #bad bad node
[root@controller(magdeburg*) ~]# 
```

```
[root@controller(magdeburg*) ~]# cat .ssh/config 
UserKnownHostsFile /dev/null
Host *
    StrictHostKeyChecking no
LogLevel QUIET
```

This is not the desired behavior as you can understand

**Comment by brunopereira81** [comment]
This is still the same:

```
[root@controller(150280*) repositories]# ssh storage01
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
42:17:a6:93:d9:b3:07:ce:9c:b1:a2:d1:ef:87:db:1c.
Please contact your system administrator.
Add correct host key in /root/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /root/.ssh/known_hosts:1
Password authentication is disabled to avoid man-in-the-middle attacks.
Keyboard-interactive authentication is disabled to avoid man-in-the-middle attacks.
```

Using the suggested options for `ssh` returns the same issues as commented on top:

```
[root@controller(150280*) repositories]# ssh storage01 #good node
Last login: Thu Jan 21 10:46:16 2016 from controller.cluster
[root@storage01 ~]# logout
[root@controller(150280*) repositories]# ssh storage01a #non-exiting node
[root@controller(150280*) repositories]# ssh storage02 #good node, not accessible, shutdown
[root@controller(150280*) repositories]# 
```

```
[root@controller(150280*) repositories]# cat ~/.ssh/config 
UserKnownHostsFile /dev/null
Host *
    StrictHostKeyChecking no
LogLevel QUIET
```
