### ISSUE TITLE
User access fails after password reset

### ISSUE THREAD

**Issue by Marc69** [clustervision/trinity#769]
**Version:** r8_fixes r8.2-63-g46084cf
**Environment:** amaster
```
[root@login ~]# obol -w system user reset --password 1234 john
[root@login ~]# ssh john@login.vc-a
The authenticity of host 'login.vc-a (172.16.255.254)' can't be established.
ECDSA key fingerprint is ee:0c:f1:97:4e:01:73:ff:57:39:0f:53:80:27:c5:47.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'login.vc-a,172.16.255.254' (ECDSA) to the list of known hosts.
john@login.vc-a's password: 
Permission denied, please try again.
john@login.vc-a's password: 
Permission denied, please try again.
john@login.vc-a's password: 

```

Ssh-ing was possible before the password reset; afterwards, neither the new nor the old password gives access.

**Comment by hansthen** [comment]
Fixed in commit 127d185ee75 (which is in r7_fixes).

**Comment by Marc69** [comment]
Still not working:
**Version:** r7_fixes r7.1-54-gcc8f928
**Environment:** tmaster

```
[root@login ~]# obol -w system user add  --password harry --sn harry harry
[root@login ~]# ssh harry@login-a
The authenticity of host 'login-a (172.16.255.254)' can't be established.
ECDSA key fingerprint is 1a:bc:5c:77:05:c9:da:b2:4b:1b:83:26:2e:63:0e:37.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'login-a,172.16.255.254' (ECDSA) to the list of known hosts.
harry@login-a's password: 
Creating home directory for harry.
[harry@login ~]$ exit
logout
Connection to login-a closed.
[root@login ~]# obol -w system user reset  --password dick harry
[root@login ~]# ssh harry@login-a
harry@login-a's password: 
Permission denied, please try again.
harry@login-a's password: 
Permission denied, please try again.
harry@login-a's password: 
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
```
